### ISSUE TITLE
Pressing ESC while in code mode should clear the text and exit code mode

### ISSUE THREAD

**Issue by MadaraUchiha** [rlemon/se-chat-dark-theme-plus#12]
Without code mode, you get this bit of functionality from chat: If you start typing a message and you give up on it, you can press ESC to instantly clear the textarea.

This doesn't happen while in code mode.

I propose that pressing ESC while in code mode with the editor in focus would exit code mode and clear the text area.

**Comment by rlemon** [comment]
should it clear tho?? I understand this is how the current input works, but maybe make it exit, and then when you hit esc again the chat resumes business as usual and clears it. *some* people may assume esc just escapes the mode.

**Comment by MadaraUchiha** [comment]
Well, you can already escape the mode by hitting CTRL+K again.

**Comment by rlemon** [comment]
fixed in 0.0.4.11
