### ISSUE TITLE
Explicitly list all "clike" languages in code editor's language drop down list

### ISSUE THREAD

**Issue by mangstadt** [rlemon/se-chat-dark-theme-plus#13]
CodeMode considers the following languages to have similar enough syntax to warrant treating them all as a single language.  When entering code in one of these languages, you have to select "clike" from the language dropdown list.

* C
* C++
* Objective-C
* Java
* Scala
* Kotlin
* Ceylon

This issue suggests that these languages be explicitly listed in the selection list for usability purposes (even if they're all using the same syntax highlighter under the hood).

**Comment by rlemon** [comment]
added in 0.0.4.11
