### ISSUE TITLE
Replace "user portrait loading" spinner

### ISSUE THREAD

**Issue by mangstadt** [rlemon/se-chat-dark-theme-plus#14]
When you click on a user's profile picture, either in the pane on the right side of the screen, or to the left of a chat message, a spinner animation is displayed until a slightly higher resolution image of the user's portrait is downloaded.  The spinner looks grainy against a dark background because it's meant to be placed on top of a white background.

This issue suggests that the spinner be replaced with the new animation used in Issue 8, or something else.

A screenshot could not be obtained due to the speed at which the portraits download.  However, it looks similar to the "image loading" spinner.

**Comment by rlemon** [comment]
fixed in 0.0.4.11
