### ISSUE TITLE
Imgur webms with .mp4 extension don't one box.

### ISSUE THREAD

**Issue by HorizonShadow** [rlemon/se-chat-dark-theme-plus#21]
`.mp4` is a valid extension for videos on imgur, but they don't onebox in chat.

http://i.imgur.com/pPwxJvf.gifv

is the same as

http://i.imgur.com/pPwxJvf.mp4

**Comment by rlemon** [comment]
This was a semi-recent change in imgur. I will add mp4 to the list of video files to play. Thanks.

**Comment by rlemon** [comment]
fixed with 71ecc824ce0ca60d4ff02e864316ee486c518a5d
