### ISSUE TITLE
"X hours later" label is too dark

### ISSUE THREAD

**Issue by mangstadt** [rlemon/se-chat-dark-theme-plus#27]
![screen shot 2016-10-15 at 6 03 25 pm](https://cloud.githubusercontent.com/assets/700174/19413678/f15a6fea-9301-11e6-8449-96d51bcbd259.png)

**Comment by rlemon** [comment]
I'll take a look. thanks.

**Comment by rlemon** [comment]
as always, Please allow upto an hour for the webstore to reflect these changed.

**Comment by mangstadt** [comment]
Looks better now, thanks! :D
