### ISSUE TITLE
Custom mention highlight colours

### ISSUE THREAD

**Issue by xbenjii** [rlemon/se-chat-dark-theme-plus#34]
Keep thinking I've highlighted random text.

`<input type="color">` in the options.

**Comment by rlemon** [comment]
the only reason I'm hesitant on this one is because then it opens up a can of worms on "well, why isn't this also customizable?"  -- can't we just decide on a better default?

**Comment by xbenjii** [comment]
Yeah, customisation is a hard one. The default colour can be really subjective though. Would the SO orange be too much?

**Comment by rlemon** [comment]
make a pr for the orange. we'll see how it works for a bit, but if I get too many complaints I'll toss you under the buss so hard :D

**Comment by xbenjii** [comment]
Like I said in chat, it's a personal preference. Nobody else has complained about it so I'll just close this :)
