### ISSUE TITLE
Replace "image loading" spinner

### ISSUE THREAD

**Issue by mangstadt** [rlemon/se-chat-dark-theme-plus#8]
The loading animation that is displayed when the browser is downloading an image is designed to look good against a white background.  It looks a little grainy when displayed on a black background.

![](http://i.imgur.com/DDblmwp.png)

**Comment by rlemon** [comment]
Do you have a suggestion?

**Comment by Patsy-issa** [comment]
We could get something from http://www.ajaxload.info/ for a quickfix

**Comment by rlemon** [comment]
chat replaces the SRC of the image for the spinner, I don't think it will be an issue, but it would still cause a 'flicker/delay' when swapping from the old spinner to the new spinner. And hopefully we don't run into race conditions where we are replacing the 'spinner' while the chat loads the proper url.

**Comment by rlemon** [comment]
http://i.imgur.com/d0AzeJN.gifv if this is okay we can put the issue to bed.

**Comment by mangstadt** [comment]
lol you love that new pond, don't you. xD

**Comment by rlemon** [comment]
will update extension shortly.
