### ISSUE TITLE
code mode [enter] needs to be considered. 

### ISSUE THREAD

**Issue by rlemon** [rlemon/se-chat-dark-theme-plus#9]
currently enter drops a new line, we can revert to the classic shift+enter for new line, or we can make that a shortcut for submit. or other? ideas? pushing the 'send' button is lame.

**Comment by HorizonShadow** [comment]
Control + Enter.

**Comment by MadaraUchiha** [comment]
:+1:  for CTRL+Enter.

**Comment by rlemon** [comment]
implemented in 0.0.4.11
